FROM python:3.8.3-slim-buster

RUN apt update && apt install nano -y

LABEL maintainer=TOMEK

# make dir /app and set it as WORKDIR

# run mkdir not necessary
RUN mkdir /app
WORKDIR /app

#copy directory my_data to current dir from WORKDIR

COPY my_data/ my_data/

EXPOSE 8000
WORKDIR /app/my_data

# -u give python standard output
CMD python -u srv.py

