version: '3.0'
services:
  api:
    image: technical/json-server:0.0.1
    build: 
        context: api/
        dockerfile: Dockerfile-api
    ports:
      - "3333:3333"
    volumes:
      - ./api/big_db.json:/api/db.json
    environment:
      - PORT=3333
  test:
    image: api-test:0.0.1
    build: 
        context: test/
        dockerfile: Dockerfile-test
    environment:
      - API_PORT=3333
      - API_HOST=http://api
    depends_on: 
      - api
    command: pytest . 
  