FROM node:latest

WORKDIR /api

#COPY db.json .

# copying multiple number of files COPY ["file1", "file2", ... , "destination path"]

COPY ["db.json", "./"]

EXPOSE 3000

RUN npm install -g json-server

CMD json-server --watch db.json --host 0.0.0.0

